---
title: "Untitled"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)
#knitr::opts_knit$set(root.dir = 'C:/Users/Geissingere/Documents/Projects/Temperature-Project')
knitr::opts_knit$set(root.dir = 'C:/Users/lewiske/Documents/CAFE/projects/temperature/river_closures')
options(knitr.kable.NA = '')

library(tidyverse)
library(lubridate)
library(knitr)
# library(pandoc)
# library(kableExtra)
library(ggpubr)
library(leaflet)

```



```{r load data, include = FALSE}
## Station data
source("./Rcode/data-cleaning/1_hobolink_station_combo_2023.R")

hobo <- hobo23 |> 
  # filter out temperature when sensor is out of water
  mutate(out.of.water = 0,
         out.of.water = replace(out.of.water, WaterLevel_meters <=0, 1))
```



```{r water level filter}
# in the winter, if water < -1, then its air and not in the water
t2 <- hobo |>
  mutate(out.of.water = replace(out.of.water, WaterTemperature_C < -1, 1)) |> 
  mutate(WaterTemperature_C = replace(WaterTemperature_C, WaterTemperature_C < -100, NA),
         WaterTemperature_C = replace(WaterTemperature_C, WaterTemperature_C > 100, NA))



```



```{r filter check 2, warning = FALSE, echo = FALSE}

SNlist <- unique(hobo$Serial)

# html file has two figs.  First is all data; second all data but with removed data in red; 

for (i in seq_along(SNlist)) {
  p1 <- hobo |>
    filter(Serial == SNlist[i]) |>
    filter(!is.na(WaterTemperature_C)) |>
    ggplot() +
    geom_point(aes(x = Time, y = WaterTemperature_C)) +
    # ggtitle(paste(hobo$Recording[hobo$Serial==SNlist[i]], SNlist[i], hobo$Station[hobo$Serial == SNlist[i]])) +
   ggtitle(paste(hobo$River.Name[hobo$Serial==SNlist[i]], SNlist[i], hobo$Station[hobo$Serial == SNlist[i]])) +

    ylim(min(hobo$WaterTemperature_C[hobo$Serial == SNlist[i]], na.rm = TRUE),
         max(hobo$WaterTemperature_C[hobo$Serial == SNlist[i]], na.rm = TRUE)) +
    xlim(min(hobo$Time[hobo$Serial == SNlist[i]], na.rm = TRUE),
         max(hobo$Time[hobo$Serial == SNlist[i]], na.rm = TRUE))
  # p2 <- t2 |>
  #   filter(Serial == SNlist[i]) |>
  #   filter(!is.na(Temp.C)) |>
  #   ggplot() +
  #   geom_point(aes(x = Time, y = Temp.C)) +
  #   ggtitle(paste(t1$Recording[t1$Serial==SNlist[i]], SNlist[i], t1$Station[t1$Serial == SNlist[i]])) +
  #   ylim(min(t1$Temp.C[t1$Serial == SNlist[i]], na.rm = TRUE),
  #        max(t1$Temp.C[t1$Serial == SNlist[i]], na.rm = TRUE)) +
  #   xlim(min(t1$Time[t1$Serial == SNlist[i]], na.rm = TRUE),
  #        max(t1$Time[t1$Serial == SNlist[i]], na.rm = TRUE))
  p2 <- t2 |>
    filter(Serial == SNlist[i]) |>
    # filter(!is.na(Temp.C)) |>
    ggplot() +
    geom_point(aes(x = Time, y = WaterTemperature_C, colour = as.character(out.of.water))) +
    ggtitle(paste(t2$Recording[t2$Serial==SNlist[i]], SNlist[i], t2$Station[t2$Serial==SNlist[i]]))  +
    ylim(min(t2$WaterTemperature_C[t2$Serial == SNlist[i]], na.rm = TRUE),
         max(t2$WaterTemperature_C[t2$Serial == SNlist[i]], na.rm = TRUE)) +
    xlim(min(t2$Time[t2$Serial == SNlist[i]], na.rm = TRUE),
         max(t2$Time[t2$Serial == SNlist[i]], na.rm = TRUE)) +
    scale_color_manual(values = c("black", "red", "darkorange")) +
    theme(legend.position = "bottom")

  p <- ggarrange(p1, p2, nrow = 1)
  print(p)

}
```



```{r write data}

#hobo23 - changed hobo23 to test to determine why error occurs
 hobo23 <- t2 |>
  dplyr::select(Station, Serial, Time.UTC, WaterPressure_kPa, DiffPressure_kPa, WaterTemperature_C, WaterLevel_meters, BarometricPressure_kPa, Rain_mm, Time, AirTemperature_C, SFA, River.Name, River.Number, dply_dt_tm, lat, long, out.of.water)

write.csv(hobo23, "./data-working/output/hobo-station-data-2023-combined.csv", row.names = FALSE)
```
